name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn --ignore-scripts
        shell: bash
      - name: Generating typechain
        run: yarn hardhat typechain
      # - name: Create local node and deploy
      #   run: |
      #     yarn hardhat node &
      #     yarn hardhat run scripts/deploy.ts --network localhost
      - name: Run Tests
        run: yarn hardhat test
  check:
    name: Foundry test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv
